apiVersion: v1
kind: ReplicationController
metadata:
  name: httpd-replicationcontroller-t3q5
spec:
  selector:
    app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd-container
          image: httpd:latest
  replicas: 1