apiVersion: v1
kind: Service
metadata:
  namespace: jenkins
  name: jenkins-service
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30008
      targetPort: 8080
  selector:
    app: jenkins