apiVersion: v1
kind: Service
metadata:
  name: web-devops
spec:
  type: NodePort
  selector:
    # Service selects the pod by labels, so add a label to pod
    app: web-devops
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008