apiVersion: v1
kind: Service
metadata:
  name: iron-db-service-nautilus
  namespace: iron-namespace-nautilus
spec:
  selector:
   db: mariadb  
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP