apiVersion: v1
kind: Service
metadata:
  name: tomcat-service-nautilus
  namespace: tomcat-namespace-nautilus
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 32227
      targetPort: 8080
  selector:
    app: tomcat