apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php-redis
  template:
   metadata:
     labels:
       app: php-redis
   spec:
     containers:
       - name: php-redis-nautilus
         image: gcr.io/google-samples/gb-frontend@sha256:a908df8486ff66f2c4daa0d3d8a2fa09846a1fc8efd65649c0109695c7c5cbff
         resources:
           requests:
             cpu: 100m
             memory: 100Mi
         env:
           - name: GET_HOSTS_FROM
             value: dns
         ports:
           - containerPort: 80
    