apiVersion: apps/v1
kind: Deployment
metadata:
  name: iron-db-deployment-nautilus
  namespace: iron-namespace-nautilus
  labels:
    db: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
     db: mariadb
  template:
    metadata:
      labels: 
           db: mariadb
    spec:
      containers:
        - name: iron-db-container-nautilus
          image: kodekloud/irondb:2.0
          env:
            - name: MYSQL_DATABASE
              value: database_web
            - name: MYSQL_ROOT_PASSWORD
              value: xsw@#90OKM12
            - name: MYSQL_PASSWORD
              value: zaq!@90OKM!2
            - name: MYSQL_USER
              value: epadmin
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: db
      volumes:
       - name: db
         emptyDir:
           {}
    