apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx-app
spec:
  selector:
    matchLabels:
     app: nginx_app 
  template:
    metadata:
      name: pod-nginx
      labels:
        app: nginx_app
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest