apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
spec:
  replicas: 2
  selector:
    matchLabels:
     db: redis-slave
  template:
   metadata:
     labels:
       db: redis-slave
   spec:
     containers:
       - name: slave-redis-nautilus
         image: gcr.io/google_samples/gb-redisslave:v3
         resources:
          requests: 
           cpu: 100m
           memory: 100Mi
         env:
           - name: GET_HOSTS_FROM
             value: dns
         ports:
           - containerPort: 6379
           
    