apiVersion: v1
kind: Pod
metadata:
  name: nginx-phpfpm
  labels:
    app: nginx
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-config-volume
          subPath: nginx.conf
        - mountPath: /var/www/html
          name: shared-files
    
    - name: php-fpm-container
      image: php:8.2-fpm-alpine
      volumeMounts:
        - mountPath: /var/www/html
          name: shared-files
  volumes:
    - name: shared-files
      emptyDir:
        {}
    - name: nginx-config-volume
      configMap:
        name: nginx-config