apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  labels:
    app: httpd_app
spec:
  containers:
    - name: httpd-container
      image: httpd:latest
      resources:
        requests:
          cpu: "100m"  # 100 milliCPU (0.1 CPU core)
          memory: "15Mi" # 128 MiB
        limits:
          cpu: "100m"  # 500 milliCPU (0.5 CPU core)
          memory: "20Mi" # 256 MiB