apiVersion: v1
kind: Pod
metadata:
  name: secret-nautilus
spec:
  containers:
    - name: secret-container-nautilus
      image: fedora:latest
      command: [ "sleep", "3600" ]
      volumeMounts:
        - mountPath: /opt/demo
          name: secret-demo
  volumes:
    - name: secret-demo
      secret:
        secretName: media