apiVersion: v1
kind: Pod
metadata:
  name: volume-share-devops
spec:
 containers:
   - name: volume-container-devops-1
     image: debian:latest
     command: ["sleep", "3600"]
     volumeMounts:
       - mountPath: /tmp/ecommerce
         name: volume-share
   - name: volume-container-devops-2
     image: debian:latest
     command: ["sleep", "3600"]
     volumeMounts:
        - mountPath: /tmp/cluster
          name: volume-share
 volumes:
    - name: volume-share
      emptyDir: {}
        