apiVersion: v1
kind: Pod
metadata:
  name: time-check
  namespace: nautilus
spec:
  containers:
    - name: time-check
      image: busybox:latest
      command: ["/bin/sh", "-c"]
      args:
        - while true; do date >> /opt/dba/time/time-check.log; sleep $TIME_FREQ; done
      env:
        - name: TIME_FREQ
          valueFrom:
            configMapKeyRef:
              name: time-config
              key: TIME_FREQ
      volumeMounts:
        - mountPath: /opt/dba/time
          name: log-volume
  volumes:
    - name: log-volume
