apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  mysql-root-password: cm9vdHBhc3M=        # rootpass (base64)
  mysql-database: d2Vic2l0ZQ==             # website (base64)
  mysql-user: dXNlcg==                     # user (base64)
  mysql-password: dXNlcjEyMw==             # user123 (base64)
  mysql-host: bXlzcWwtc2VydmljZQ==         # mysql-service (base64)
